export const ROUTES = {
  ABOUT: "/about",
  APIS: "/apis",
  CONTACT: "/contact",
  CONTRIBUTE: "/contribute",
  DCP_UPDATES: "/dcp-updates",
  GUIDES: "/guides",
  HCA_BIONETWORKS: "/hca-bio-networks",
  HELP: "/help",
  METADATA: "/metadata",
  METADATA_CELL_ANNOTATION: "/metadata/cell-annotation",
  METADATA_TIER_1: "/metadata/tier-1",
  METADATA_TIER_2: "/metadata/tier-2",
  PRIVACY: "/privacy",
  SEARCH: "/search",
};
