export const BLACK_RGB = "rgb(0, 0, 0)";
export const FONT_BLACK_RBG = "rgb(32, 33, 36)";
export const PRIMARY_RGB = "rgb(28, 124, 199)";
export const TEST_ID_HEADER_NAVIGATION = "navigation";
export const TEST_ID_HEADER_SOCIALS = "socials";
export const TEST_ID_HOMEPAGE_METRIC = "metric";
export const TEST_ID_HOMEPAGE_TILE = "tile";
export const TEST_ID_METADATA_SEARCH_INPUT = "metadata-search";
export const TEST_ID_METADATA_SEARCH_RESULTS = "metadata-search-results";
export const TEST_ID_PAGE_NAVIGATION = "page-navigation";
export const TEST_ID_PAGE_OUTLINE = "page-outline";
export const TEST_ID_PAGE_TAB = "tab";
export const TEST_ID_SHOW_REQUIRED_FIELDS = "show-required-fields";
export const TEST_BASE_URL = "/"; // TODO: process.env.GATSBY_PORTAL_URL
