name: Test build
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: main
      - uses: actions/checkout@v2
        with:
          repository: HumanCellAtlas/metadata-schema
          path: hca-metadata-schema
      - uses: actions/setup-node@v2
        with:
          node-version: "14.16.0"
      
      - run: |
          cd main
          npm ci
          npm install --global gatsby-cli
          source ./set-dev-env.sh && gatsby build --verbose